# Generated by Django 3.1 on 2020-10-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
